# Generated by Django 4.1.5 on 2023-01-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_user_groups_alter_user_user_permissions'),
        ('school_process', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProggressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progress_type', models.CharField(choices=[('Attendance ', 'Attendance '), ('Punctuality', 'Punctuality'), ('Effort', 'Effort'), ('Behaviour', 'Behaviour'), ('Homework', 'Homework'), ('Quiz', 'Quiz')], max_length=30)),
                ('score', models.CharField(choices=[('Unacceptable', 'Unacceptable'), ('On Level', 'On Level'), ('Off Level', 'Off Level')], default='On Level', max_length=30)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='school_process.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='accounts.studentprofile')),
            ],
        ),
    ]
