# Generated by Django 4.1.5 on 2023-01-22 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_process', '0002_lesson'),
        ('progress_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_type', models.CharField(choices=[('Attendance ', 'Attendance '), ('Punctuality', 'Punctuality'), ('Effort', 'Effort'), ('Behaviour', 'Behaviour'), ('Homework', 'Homework'), ('Quiz', 'Quiz')], max_length=30)),
                ('score', models.CharField(choices=[('Unacceptable', 'Unacceptable'), ('On Level', 'On Level'), ('Off Level', 'Off Level')], default='On Level', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='proggressrecord',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='proggressrecord',
            name='progress_type',
        ),
        migrations.RemoveField(
            model_name='proggressrecord',
            name='score',
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgressScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracking.progressscore')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_process.lesson')),
            ],
        ),
    ]
