# Generated by Django 4.1.5 on 2023-01-23 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_process', '0002_lesson'),
        ('progress_tracking', '0004_remove_lessonprogress_progressscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress_list', to='school_process.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='progress_record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress_list', to='progress_tracking.proggressrecord'),
        ),
    ]
