# Generated by Django 4.1.5 on 2023-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0005_alter_lessonprogress_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='progressScore',
            field=models.ManyToManyField(blank=True, related_name='lesson_progress_list', to='progress_tracking.progressscore'),
        ),
    ]
