# Generated by Django 4.1.5 on 2023-01-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_groups_alter_user_user_permissions'),
        ('progress_tracking', '0006_alter_lessonprogress_progressscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='progress_record',
        ),
        migrations.RemoveField(
            model_name='proggressrecord',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress_list', to='progress_tracking.proggressrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress_list', to='accounts.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='student_progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress_list', to='progress_tracking.studentprogress'),
        ),
    ]
