# Generated by Django 4.0 on 2023-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0007_remove_lessonprogress_progress_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='progressScore',
            field=models.ManyToManyField(blank=True, related_name='lesson_progress_list', to='progress_tracking.ProgressScore'),
        ),
    ]
