# Generated by Django 4.1.5 on 2023-02-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0008_alter_lessonprogress_progressscore'),
        ('progress_tracking', '0008_classprogress_proggressrecord_class_progress'),
    ]

    operations = [
    ]
