# Generated by Django 4.1.5 on 2023-01-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('class_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=55)),
                ('student_last_name', models.CharField(max_length=55)),
                ('health_insurance', models.CharField(max_length=55)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('year_of_entry', models.CharField(max_length=25)),
                ('period', models.CharField(max_length=25)),
                ('surname_doe', models.CharField(max_length=55)),
                ('guardian_first_name', models.CharField(max_length=55)),
                ('guardian_last_name', models.CharField(max_length=55)),
                ('guardian_address', models.CharField(max_length=255)),
                ('home_phone_no', models.CharField(max_length=25)),
                ('guardian_mobile_no', models.CharField(max_length=25)),
                ('previous_school_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('starting_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission_process.class')),
            ],
        ),
    ]
