# Generated by Django 4.1.5 on 2023-01-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
