# Generated by Django 4.1.5 on 2023-01-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_process', '0001_initial'),
        ('accounts', '0013_alter_studentprofile_class_id'),
        ('admission_process', '0002_admissionapplication_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_process.class'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
