# Generated by Django 4.1.5 on 2023-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_process', '0003_alter_admissionapplication_class_name_delete_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Appointment', 'Appointment')], default='Present', max_length=25),
        ),
    ]
