# Generated by Django 4.1.5 on 2023-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_process', '0004_admissionapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Appointment', 'Appointment')], default='Received', max_length=25),
        ),
    ]
