# Generated by Django 4.0 on 2023-02-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_process', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Wating', 'Wating'), ('Accept', 'Accept The Appoinment'), ('Reject', 'Reject')], default='Wating', max_length=55),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.IntegerField(choices=[(0, '09:00 AM'), (1, '10:00 AM'), (2, '11:00 AM'), (3, '12:00 PM'), (4, '01:00 PM'), (5, '02:00 PM'), (6, '03:00 PM'), (7, '04:00 PM'), (8, '05:00 PM')]),
        ),
    ]
