# Generated by Django 4.1.5 on 2023-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_process', '0007_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reject_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
