# Generated by Django 4.1.5 on 2023-02-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_process', '0008_appointment_reject_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Appointment', 'Appointment'), ('Appointment Received', 'Appointment Received'), ('Academic Received', 'Academic Received'), ('Success', 'Success')], default='Received', max_length=25),
        ),
    ]
