# Generated by Django 4.0 on 2023-01-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_groups_alter_user_user_permissions'),
        ('school_process', '0002_class_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_type', models.CharField(choices=[('Regular', 'Regular'), ('Early', 'Early')], default='Regular', max_length=25)),
                ('notes', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.studentprofile')),
            ],
        ),
    ]
