# Generated by Django 4.1.5 on 2023-02-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_process', '0002_lesson'),
        ('school_process', '0004_dismissal_status_alter_dismissal_dismissal_type'),
    ]

    operations = [
    ]
