# Generated by Django 4.1.5 on 2023-02-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_process', '0005_merge_20230203_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_dismissial_list', to='school_process.class')),
            ],
        ),
        migrations.AddField(
            model_name='dismissal',
            name='class_progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissial_list', to='school_process.classdismissal'),
        ),
    ]
