# Generated by Django 4.1.5 on 2023-02-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_process', '0007_alter_classdismissal__class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dismissal',
            old_name='class_progress',
            new_name='class_dismissal',
        ),
    ]
