# Generated by Django 4.1.5 on 2023-02-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_process', '0005_merge_20230203_0420'),
        ('school_process', '0008_rename_class_progress_dismissal_class_dismissal'),
    ]

    operations = [
    ]
