# Generated by Django 4.1.5 on 2023-02-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_process', '0009_merge_20230204_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dismissal',
            name='class_dismissal',
        ),
        migrations.DeleteModel(
            name='ClassDismissal',
        ),
    ]
