# Generated by Django 4.0 on 2023-02-03 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incident_accident_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentaccidentreport',
            old_name='send_mail_parent',
            new_name='send_mail_guardian',
        ),
        migrations.RenameField(
            model_name='incidentaccidentreport',
            old_name='send_notification_parent',
            new_name='send_notification_guardian',
        ),
        migrations.AddField(
            model_name='incidentaccidentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentaccidentreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
