# Generated by Django 4.1.5 on 2023-01-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminprofile_created_at_adminprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalprofile',
            name='appointed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
