# Generated by Django 4.1.5 on 2023-01-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission_process', '0002_admissionapplication_is_active'),
        ('accounts', '0010_guardianprofile_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission_process.class'),
        ),
    ]
