# Generated by Django 4.1.5 on 2023-02-21 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('accounts', 'Accounts'), ('classes', 'Classes'), ('teams', 'Teams'), ('pearson_e_textbook', 'Pearson E-Text Book'), ('uniforms', 'Uniforms'), ('fees', 'Fees'), ('books', 'Books'), ('student_documents', "Student's Documents"), ('homework', 'Homework'), ('classroom_concerns', 'Classroom Concerns'), ('academic_progress', 'Academic Progress'), ('violence', 'Violence'), ('bullying', 'Bullying'), ('identifying_special_needs', 'Identifying Special Needs'), ('uniform_issue', 'Unioform Issue'), ('student_absence', 'Student Absence'), ('teacher_rel_class_concern', 'Teacher Related Class Concerns'), ('teacher_not_communicationg', 'Teacher Not Communicationg'), ('teacher_attitude', "Teacher's Attitude with Student"), ('teacher_absence', "Teacher's Recurring Absence and Lateness"), ('academic_concern', 'Academic Concerns'), ('student_behaviour', 'Student Behaviour on Buses'), ('nanny', 'Nanny'), ('maintenance', 'Building Maintenance')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('OH', 'On Hold'), ('CL', 'Closed')], max_length=2)),
                ('closing_remarks', models.TextField(blank=True)),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='assignees')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
