# Generated by Django 4.1.5 on 2023-02-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('OH', 'On Hold'), ('CL', 'Closed')], default='AC', max_length=2),
        ),
    ]
