# Generated by Django 4.1.5 on 2023-02-22 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_support', '0003_ticketconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_closer', to=settings.AUTH_USER_MODEL),
        ),
    ]
