# Generated by Django 4.1.5 on 2023-02-12 02:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_user_groups_alter_user_user_permissions'),
        ('school_process', '0009_merge_20230204_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_grade_list', to='school_process.class')),
            ],
        ),
        migrations.CreateModel(
            name='GradingKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=30)),
                ('starting_mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('finish_mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.CreateModel(
            name='GradingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('effect', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_grade_list', to='grading_and_reports.classgrades')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade_list', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LessonGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_grade_list', to='school_process.lesson')),
                ('student_grades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_grade_list', to='grading_and_reports.studentgrades')),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grading_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_list', to='grading_and_reports.gradingtype')),
                ('lesson_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_list', to='grading_and_reports.lessongrade')),
            ],
        ),
    ]
