# Generated by Django 4.1.5 on 2023-02-12 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_and_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingkey',
            name='finish_mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
