# Generated by Django 4.1.5 on 2023-02-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading_and_reports', '0002_alter_gradingkey_finish_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrades',
            name='class_grades',
        ),
        migrations.DeleteModel(
            name='ClassGrades',
        ),
    ]
