# Generated by Django 4.1.5 on 2023-01-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='lesson',
            new_name='lesson_period',
        ),
    ]
