# Generated by Django 4.1.5 on 2023-02-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_classattendance_attendance_class_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_attendance',
        ),
        migrations.DeleteModel(
            name='ClassAttendance',
        ),
    ]
